### ISSUE TITLE
Create API for Movie Metadata

### ISSUE THREAD

**Issue by rschlaefli** [kwizapp/metadata-service#6]
### Related User Story & Issues
Story: https://github.com/kwizapp/kwiz/issues/5

### Description

Add an API endpoint that returns movie metadata for a specific Imdb ID, or, if none is provided, for a random movie.

### Tasks

- [x] Build a basic API that fetches movies from the database based on Imdb ID
- [x] Add integration tests for the database interactions 
- [x] Add validation of the Imdb ID based on common library code
