### ISSUE TITLE
Implement fetching of n different movies

### ISSUE THREAD

**Issue by rschlaefli** [kwizapp/metadata-service#8]
### Description

Given an ImdbId, the service should return `n` movies that are different (i.e., don't have the same id).

### Tasks

- [x] Extend the random id generator with the possibility of generating multiple random ids
- [x] Extend the random id generator with the possibility of filtering ids (`WHERE`) for ids, release year, etc.
- [x] Implement functionality that fetches a number of different movies using the random id generator

### Context

https://github.com/kwizapp/kwiz/issues/23
