### ISSUE TITLE
Implement fetching of n related movies

### ISSUE THREAD

**Issue by rschlaefli** [kwizapp/metadata-service#9]
### Description

To display interesting facts and generate useful questions, it could be useful to use related movies instead of purely random movies. For example, on an easy difficulty level, it could be sensible to use movies from the same time segment and genre.

### Tasks

- [ ] Implement heuristics for the computation of "relatedness"
- [ ] Implement functionality that can get a list of top-n movies ranked by "relatedness"
- [ ] Allow the user to define the means of "relatedness" with parameters (e.g., same genre, same date segment, ...)
- [ ] Allow the user to reverse the ranking to get the most unrelated movies (e.g., to increase difficulty)

### Context

https://github.com/kwizapp/kwiz/issues/23
